# Generated by Django 4.2.7 on 2025-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=10)),
                ('Roll_Number', models.ImageField(upload_to='')),
                ('Course', models.CharField(max_length=8)),
                ('Branch', models.CharField(max_length=15)),
                ('Year', models.DateField()),
            ],
        ),
    ]
