# Generated by Django 4.2.7 on 2025-04-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_studentsignup_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='Name',
            field=models.CharField(max_length=100),
        ),
    ]
