# Generated by Django 4.2.7 on 2025-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_studentsignup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='Roll_Number',
            field=models.IntegerField(),
        ),
    ]
