# Generated by Django 4.2.7 on 2025-04-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_studentsignup_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsignup',
            name='Roll_Number',
            field=models.CharField(max_length=15),
        ),
    ]
