# Generated by Django 4.2.7 on 2025-04-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alumnisignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnisignup',
            name='passedout',
            field=models.IntegerField(),
        ),
    ]
