# Generated by Django 4.2.7 on 2025-04-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_alumnisignup_passedout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_Picture', models.ImageField(upload_to='profile_pictures/')),
                ('name', models.CharField(max_length=30)),
                ('passedout', models.IntegerField()),
                ('degree', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('job_title', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('linkedin_profile', models.URLField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
