# Generated by Django 4.2.7 on 2025-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_job_title_alumni_profile_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_company', models.CharField(max_length=30)),
                ('job_location', models.CharField(max_length=30)),
                ('job_salary', models.IntegerField()),
                ('job_type', models.CharField(max_length=30)),
                ('job_experience', models.IntegerField()),
                ('job_skills', models.TextField()),
                ('job_description', models.TextField()),
            ],
        ),
    ]
