# Generated by Django 4.2.7 on 2025-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_job_posting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_posting',
            name='job_experience',
            field=models.CharField(max_length=30),
        ),
    ]
