# Generated by Django 4.2.7 on 2025-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_job_posting_job_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_title', models.CharField(max_length=30)),
                ('internship_company', models.CharField(max_length=30)),
                ('internship_location', models.CharField(max_length=30)),
                ('internship_duration', models.CharField(max_length=30)),
                ('internship_type', models.CharField(max_length=30)),
                ('internship_start_date', models.DateField()),
                ('internship_eligibility', models.TextField()),
                ('internship_description', models.TextField()),
            ],
        ),
    ]
