# Generated by Django 4.2.7 on 2025-04-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('name', models.CharField(max_length=30)),
                ('cgpa', models.FloatField()),
                ('backlogs', models.IntegerField()),
                ('attendance', models.IntegerField()),
                ('year', models.CharField(max_length=30)),
                ('roll_number', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
