# Generated by Django 4.2.7 on 2025-04-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_student_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_profile',
            old_name='backlogs',
            new_name='arrear_history',
        ),
        migrations.AddField(
            model_name='student_profile',
            name='standing_arrear',
            field=models.BooleanField(default=False),
        ),
    ]
