# Generated by Django 4.2.7 on 2025-04-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_backlogs_student_profile_arrear_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='attendance',
            field=models.FloatField(),
        ),
    ]
