# Generated by Django 4.2.7 on 2025-04-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_student_profile_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career_Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_title', models.CharField(max_length=30)),
                ('resource_description', models.TextField()),
                ('resource_type', models.CharField(max_length=30)),
                ('resource_file', models.FileField(upload_to='resource_files/')),
                ('youtube_link', models.URLField(max_length=30)),
            ],
        ),
    ]
