# Generated by Django 4.2.7 on 2025-04-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_career_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upcoming_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_document', models.FileField(upload_to='event_documents/')),
                ('event_primary_image', models.ImageField(upload_to='event_primary_images/')),
                ('event_secondary_image', models.ImageField(upload_to='event_secondary_images/')),
                ('event_venue', models.CharField(max_length=30)),
                ('event_date', models.DateField()),
                ('event_title', models.CharField(max_length=30)),
            ],
        ),
    ]
