# Generated by Django 4.2.7 on 2025-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_upcoming_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_document', models.FileField(upload_to='conference_documents/')),
                ('conference_primary_image', models.ImageField(upload_to='conference_primary_images/')),
                ('conference_secondary_image', models.ImageField(upload_to='conference_secondary_images/')),
                ('conference_venue', models.CharField(max_length=30)),
                ('conference_date', models.DateField()),
                ('conference_alumni_name', models.CharField(max_length=30)),
            ],
        ),
    ]
