# Generated by Django 5.2 on 2025-05-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_phone', models.IntegerField()),
                ('student_department', models.CharField(max_length=30)),
                ('student_year', models.CharField(max_length=30)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_primary_image',
            field=models.ImageField(upload_to='conference_documents/'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_secondary_image',
            field=models.ImageField(upload_to='conference_documents/'),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='event_primary_image',
            field=models.ImageField(upload_to='event_documents/'),
        ),
        migrations.AlterField(
            model_name='upcoming_events',
            name='event_secondary_image',
            field=models.ImageField(upload_to='event_documents/'),
        ),
    ]
