# Generated by Django 5.2 on 2025-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_student_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial_Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=30)),
                ('campaign_description', models.TextField()),
                ('campaign_target_amount', models.IntegerField()),
            ],
        ),
    ]
